In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import os, sys

lib_path = os.path.abspath(os.path.join('..'))
sys.path.append(lib_path)

In [3]:
from usa.reader import ReadFromCSV
from usa.classifier import ClassifierBySequencePatterns, ClassifierByClosureSequencePatterns
from usa.metrics import accuracy_score_with_unclassified_objects, tpr_fpr_nonclass, f1_score_nonclass

In [4]:
file_name = '/Users/danil.gizdatullin/git_projects/HSE/UnbrokenSequenceAnalysis/examples/data/full_data_shuffle.csv'
coding_dict={'work': 1, 'separation': 2, 'partner': 3,
             'marriage': 4, 'children': 5, 'parting': 6,
             'divorce': 7, 'education': 8}

In [5]:
reader = ReadFromCSV(file_name, coding_dict)

data, label = reader.from_file_to_data_list()

In [6]:
size_of_train = int(len(data)*0.66)

In [7]:
X_train = data[:size_of_train]
X_test = data[size_of_train:]

y_train = label[:size_of_train]
y_test = label[size_of_train:]

In [10]:
f_ones = []
y_pred_list = []
for i in (1.00001, 1.5, 2, 5, 10):
    origin_clas sifier = ClassifierBySequencePatterns(number_of_classes=2,
                                                     threshold_for_rules=0.001,
                                                     threshold_for_growth_rate=i)
    origin_classifier.fit(X_train, y_train)
    y_pred = origin_classifier.predict(X_test)
    y_pred_list.append(y_pred)

3205
3205
Median = 1.510187
Median = 1.855458
3205
3205
Median = 2.367816
Median = 2.533981
3205
3205
Median = 3.078161
Median = 3.273058
3205
3205
Median = 7.103448
Median = 6.334951
3205
3205
Median = 12.312644
Median = 10.558252


In [11]:
accuracy = []
tpr_fpr = []
f1 = []

for i in y_pred_list:
    cur_accuracy = accuracy_score_with_unclassified_objects(y_test, i)
    cur_f1 = f1_score_nonclass(y_test, i)
    cur_tpr_fpr = tpr_fpr_nonclass(y_test, i)
    accuracy.append(cur_accuracy)
    f1.append(cur_f1)
    tpr_fpr.append(cur_tpr_fpr)

[[697 433]
 [239 275]]
[[466 336]
 [146 207]]
[[302 238]
 [ 83 149]]
[[134  27]
 [ 41  22]]
[[99 11]
 [30  8]]


In [12]:
accuracy

[(0.59124087591240881, 8),
 (0.58268398268398269, 497),
 (0.58419689119170981, 880),
 (0.6964285714285714, 1428),
 (0.72297297297297303, 1504)]

In [13]:
f1

[(0.45008183306055649, 8),
 (0.46205357142857145, 497),
 (0.48142164781906299, 880),
 (0.39285714285714285, 1428),
 (0.2807017543859649, 1504)]

In [14]:
tpr_fpr

[(0.53501945525291827, 0.38318584070796458, 8),
 (0.58640226628895187, 0.41895261845386533, 497),
 (0.64224137931034486, 0.44074074074074077, 880),
 (0.34920634920634919, 0.16770186335403728, 1428),
 (0.21052631578947367, 0.10000000000000001, 1504)]

In [15]:
f_ones = []
y_pred_list = []
for i in (1.00001, 1.5, 2, 5, 10):
    origin_classifier = ClassifierByClosureSequencePatterns(number_of_classes=2,
                                                            threshold_for_rules=0.001,
                                                            threshold_for_growth_rate=i)
    origin_classifier.fit(X_train, y_train)
    y_pred = origin_classifier.predict(X_test)
    y_pred_list.append(y_pred)

Median = 1.558812
Median = 1.784847
Median = 2.367816
Median = 2.533981
Median = 3.078161
Median = 3.167476
Median = 7.103448
Median = 6.334951
Median = 12.312644
Median = 10.558252


In [16]:
accuracy = []
tpr_fpr = []
f1 = []

for i in y_pred_list:
    cur_accuracy = accuracy_score_with_unclassified_objects(y_test, i)
    cur_f1 = f1_score_nonclass(y_test, i)
    cur_tpr_fpr = tpr_fpr_nonclass(y_test, i)
    accuracy.append(cur_accuracy)
    f1.append(cur_f1)
    tpr_fpr.append(cur_tpr_fpr)

[[694 436]
 [238 276]]
[[466 333]
 [145 208]]
[[301 235]
 [ 82 149]]
[[133  24]
 [ 40  21]]
[[98  7]
 [29  7]]


In [17]:
accuracy

[(0.59002433090024331, 8),
 (0.58506944444444442, 500),
 (0.58670143415906129, 885),
 (0.70642201834862384, 1434),
 (0.74468085106382975, 1511)]

In [18]:
f1

[(0.45024469820554641, 8),
 (0.46532438478747201, 500),
 (0.48455284552845523, 885),
 (0.39622641509433959, 1434),
 (0.28000000000000003, 1511)]

In [19]:
tpr_fpr

[(0.53696498054474706, 0.38584070796460179, 8),
 (0.58923512747875351, 0.41677096370463079, 500),
 (0.64502164502164505, 0.43843283582089554, 885),
 (0.34426229508196721, 0.15286624203821655, 1434),
 (0.19444444444444445, 0.066666666666666666, 1511)]

In [32]:
y_pred_proba = []

origin_classifier = ClassifierByClosureSequencePatterns(number_of_classes=2,
                                                        threshold_for_rules=0.001,
                                                        threshold_for_growth_rate=5)
origin_classifier.fit(X_train, y_train)
y_pred_proba = origin_classifier.predict_proba(X_test)

Median = 7.103448
Median = 6.334951


In [33]:
y_pred_proba

[[0, 0],
 [1.0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, inf],
 [0, 0],
 [0, 1.0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 1.0],
 [0, 0],
 [0, 0],
 [inf, 0],
 [0, 0],
 [0, 0],
 [inf, 0],
 [0, 0],
 [0, 0],
 [0, 1.0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [inf, 0],
 [0, 0],
 [0, 0],
 [inf, 0],
 [inf, 0],
 [inf, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [inf, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [inf, 0],
 [inf, 0],
 [0, 0],
 [inf, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 0],
 [0, 1.0],
 [0, 0],
 [inf

In [35]:
cntr = 0
print len(y_pred_proba)
for i in y_pred_proba:
    if i[0] > 0 and i[1] > 0:
        print i[0]
        print i[1]
        print ""
        print cntr
    cntr += 1

1652


In [50]:
y_threshold_ans = []
for i in y_pred_proba:
    if i[0] > 0:
        y_threshold_ans.append(0)
    elif abs(i[1] - i[0]) > 0.:
        y_threshold_ans.append(1)
    else:
        y_threshold_ans.append(0)

In [51]:
cur_accuracy = accuracy_score_with_unclassified_objects(y_test, y_threshold_ans)
cur_f1 = f1_score_nonclass(y_test, y_threshold_ans)
cur_tpr_fpr = tpr_fpr_nonclass(y_test, y_threshold_ans)
print (cur_accuracy)
print (cur_f1)
print (cur_tpr_fpr)

[[1113   24]
 [ 494   21]]
(0.68644067796610164, 0)
(0.075000000000000011, 0)
(0.040776699029126215, 0.021108179419525065, 0)
